spring:
  application:
    name: simple-testd
  threads:
    virtual:
      enabled: true
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:demo.yaml
    type: com.alibaba.druid.pool.DruidDataSource
